name: 'superstore_delivered'
version: '1.0.0'
config-version: 2

profile: 'superstore_delivered'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  superstore_delivered:
    duckdb:
      +materialized: view