version: 2

sources:
  - name: raw_data
    database: main    # DuckDB uses 'main' as the default schema
    tables:
      - name: crm_customers
        file: '../generated_data/crm_customers.csv'
      - name: ecommerce_products
        file: '../generated_data/ecommerce_products.csv'
      - name: ecommerce_orders
        file: '../generated_data/ecommerce_orders.csv'
      - name: ecommerce_order_details
        file: '../generated_data/ecommerce_order_details.csv'
      - name: delivery_data
        file: '../generated_data/delivery_data.csv'